const dummy = [
  {
    id: 1,
    title: "저희 사진 후기요",
    name: "킹왕짱",
    content: "저희 사진 이쁘죠???",
    nickname: "아이유",
    email: "abc@abc.com",
    img: "https://i.ibb.co/Xp8wYXL/Tiyaaa-on-Twitter.jpg",
    totalcomments: 3,
    createdAt: "2021.11.10",
  },
  {
    id: 2,
    title: "저희 이번에 촬영한 사진이에요!",
    name: "나는야 섬사람",
    content: "제가 너무 잘나왔어요",
    img: "https://i.ibb.co/N1mhbXD/ROISTUDIO-La-Brise-KOREA-PRE-WEDDING-PHOTOSHOOT-by-LOVINGYOU.jpg",
    totalcomments: 2,
  },
  {
    id: 3,
    title: "프로포즈 받았습니다~",
    name: "안산인",
    content: "꽃이쁘나요???",
    img: "https://i.ibb.co/zmVXk7k/korea-wedding-photograpghy-chungdam-studio-2019-sample-Korea-Wedding-Photography-Lim-s-Wedding-Story.jpg",
    totalcomments: 1,
  },
  {
    id: 4,
    title: "이번에 뽑아본 붕붕이",
    name: "천안인",
    content: "역시 차는 비엠",
    img: "https://i.ibb.co/WVKM8Cx/IMG-2308.jpg",
    totalcomments: 220,
  },
  {
    id: 5,
    title: "블랙 / 네이비 골라주세요!!!",
    name: "청주인",
    content: "네이비가 이쁘겠죠?ㅎㅎㅎ",
    img: "https://i.ibb.co/kyQs5qD/image.jpg",
    totalcomments: 0,
  },
  {
    id: 6,
    title: "개발자 공부 개어려움",
    name: "후루끼",
    content: "개발은 진짜 헬...",
    img: "https://i.ibb.co/gSBdmr1/2021-11-11-15-06-24.png",
    totalcomments: 10,
  },
  {
    id: 7,
    title: "사진 존예",
    name: "깡탱",
    content: "역시 사진은 영종도",
    img: "https://i.ibb.co/x5HNV5z/bride-g8bfa369fe-1920.jpg",
    totalcomments: 5,
  },
  {
    id: 8,
    title: "쓰읍",
    name: "으엥",
    content: "후하",
    img: "https://i.ibb.co/kyQs5qD/image.jpg",
    totalcomments: 0,
  },
  {
    id: 9,
    title: "와우 멋져요",
    name: "나나나나아느아안",
    content: "오예",
    img: "https://i.ibb.co/kyQs5qD/image.jpg",
    totalcomments: 7,
  },
];

export default dummy;
